# Generated by Django 5.2.1 on 2025-06-28 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comapny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('ceo', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('est_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prouct_Name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('seat_capacitiy', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=100)),
                ('milage', models.IntegerField()),
                ('Comapny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='Class_Based_Viewsapp.comapny')),
            ],
        ),
    ]
